### PR TITLE
Port to Yarn and 1.21.2

### PR DESCRIPTION
**Pull request by IMS212**

### CODE REVIEW

**Comment by LambdAurora** [comment]
Given my current tendency to switch to Mojmap + YALMM getting SpruceUI to yarn seems contrary to my goals.

**Comment by IMS212** [comment]
It will likely be easier to first move to Yarn, due to QM having bad remapping tooling. I’m looking at if I can do a direct port though.

**Comment by LambdAurora** [comment]
If you do port it, you might need to be aware of the small issues that have happened with mojmap + YALMM layering on Fabric loom 1.7+ that requires a custom mojmap mapping layer (which can be found in LambDynamicLights)

**Comment by LambdAurora** [comment]
There's no a 1.21.2 branch which is already switched to mojmap + YALMM on 1.21.1, only the actual porting is left to do.

**Comment by LambdAurora** [comment]
Ended up being treated in 6c4cd8f79fce3ed6f1a331d4bd070303c005de73.

**Pull request closed without merging**
